FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:sdk
WORKDIR /app
COPY --from=build-env /app/out .
RUN echo "{ \"ConnectionStrings\": { \"FinalApp\": \"Server=expired.database.windows.net;Database=Expired;User Id={0};Password={1};MultipleActiveResultSets=true\" } }" > appsettings.Production.json

ARG User__Id
ARG Password
ARG Send__Grid__Key
ENV ASPNETCORE_URLS http://0.0.0.0:80;https://0.0.0.0:443 

CMD ["dotnet", "FinalApp.dll"]